# Generated by Django 5.2.3 on 2025-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=models.JSONField(),
        ),
    ]
